version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak1:
    image: quay.io/keycloak/keycloak:23.0.6
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-db:5432/keycloak_db
      KC_DB_USERNAME: username
      KC_DB_PASSWORD: password
    volumes:
      - ./realm-config.json:/opt/keycloak/data/import/realm.json:ro
    ports:
      - "8080:8080" # Expose Keycloak 1's default port (8080) to the host on port 8080
    command: ["start-dev", "--import-realm", "--cache-config-file=cache-ispn.xml"]
    depends_on:
      - postgres-db

  keycloak2:
    image: quay.io/keycloak/keycloak:23.0.6
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-db:5432/keycloak_db
      KC_DB_USERNAME: username
      KC_DB_PASSWORD: password
    volumes:
      - ./realm-config.json:/opt/keycloak/data/import/realm.json:ro
    ports:
      - "8081:8080" # Expose Keycloak on a different port (8081) to avoid conflict with keycloak1
    command: ["start-dev", "--cache-config-file=cache-ispn.xml"]
    depends_on:
      - postgres-db

  keycloak-flask-app:
    build:
      context: .
      dockerfile: flask_app/Dockerfile
    ports:
      - "5000:5000"

volumes:
  postgres_data:
