version: '3.8'


networks:
  keycloak1-network:
    ipam:
      config:
        - subnet: 192.168.10.0/24
  keycloak2-network:
    ipam:
      config:
        - subnet: 192.168.20.0/24
  shared_network:
    ipam:
      config:
        - subnet: 192.168.30.0/24

services:
  nginx:
    image: nginx:latest
    networks:
      - keycloak1-network
      - keycloak2-network
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - keycloak1
      - keycloak2


  postgres-db:
    image: postgres:latest
    networks:
      - keycloak1-network
      - keycloak2-network
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak1:
    build:
      context: .
      dockerfile: Dockerfile-keycloak
    networks:
      keycloak1-network:
        ipv4_address: 192.168.10.4
      shared_network:
        ipv4_address: 192.168.30.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-db:5432/keycloak_db
      KC_DB_USERNAME: username
      KC_DB_PASSWORD: password
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm.json:ro
    ports:
      - "8081:8080"
      - "7801:7800"
    command: ["start-dev", "--import-realm", "--cache-config-file=keycloak1-cache-ispn.xml", '--log-level=org.infinispan.CLUSTER:debug']
    depends_on:
      - postgres-db

  keycloak2:
    build:
      context: .
      dockerfile: Dockerfile-keycloak
    networks:
      keycloak2-network:
        ipv4_address: 192.168.20.4
      shared_network:
        ipv4_address: 192.168.30.5
    ports:
      - "8082:8080"
      - "7802:7800"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-db:5432/keycloak_db
      KC_DB_USERNAME: username
      KC_DB_PASSWORD: password
    command: ["start-dev", "--cache-config-file=keycloak2-cache-ispn.xml", '--log-level=org.infinispan.CLUSTER:debug']
    depends_on:
      - keycloak1
      - postgres-db

  keycloak-flask-app:
    build:
      context: .
      dockerfile: Dockerfile-app
    networks:
      - keycloak1-network
      - keycloak2-network
    ports:
      - "5000:5000"

volumes:
  postgres_data:
